version: '3.1.1'
services:
  job-app:
    image: job-app.jar
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

    ports:
      - '8080:8080'

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
